// #define DEFINE( down_width, right_width, up_width, left_width, code ) put-it-somewhere

DEFINE( 0, 0, 0, 0, " " );
        
DEFINE( 0, 1, 0, 1, "\u2500" );
DEFINE( 0, 2, 0, 2, "\u2501" );
DEFINE( 1, 0, 1, 0, "\u2502" );
DEFINE( 2, 0, 2, 0, "\u2503" );

    // 2504 ... 250B -> triple dash chars.

DEFINE( 1, 1, 0, 0, "\u250C" );
DEFINE( 1, 2, 0, 0, "\u250D" );
DEFINE( 2, 1, 0, 0, "\u250E" );
DEFINE( 2, 2, 0, 0, "\u250F" );
        
DEFINE( 1, 0, 0, 1, "\u2510" );
DEFINE( 1, 0, 0, 2, "\u2511" );
DEFINE( 2, 0, 0, 1, "\u2512" );
DEFINE( 2, 0, 0, 2, "\u2513" );
        
DEFINE( 0, 1, 1, 0, "\u2514" );
DEFINE( 0, 2, 1, 0, "\u2515" );
DEFINE( 0, 1, 2, 0, "\u2516" );
DEFINE( 0, 2, 2, 0, "\u2517" );
        
DEFINE( 0, 0, 1, 1, "\u2518" );
DEFINE( 0, 0, 1, 2, "\u2519" );
DEFINE( 0, 0, 2, 1, "\u251A" );
DEFINE( 0, 0, 2, 2, "\u251B" );
        
DEFINE( 1, 1, 1, 0, "\u251C" );
DEFINE( 1, 2, 1, 0, "\u251D" );
DEFINE( 1, 1, 2, 0, "\u251E" );
DEFINE( 2, 1, 1, 0, "\u251F" );     // ?
        
DEFINE( 2, 1, 2, 0, "\u2520" );
DEFINE( 1, 2, 2, 0, "\u2521" );     // ?
DEFINE( 2, 2, 1, 0, "\u2522" );
DEFINE( 2, 2, 2, 0, "\u2523" );

DEFINE( 1, 0, 1, 1, "\u2524" );
DEFINE( 1, 0, 1, 2, "\u2525" );
DEFINE( 1, 0, 2, 1, "\u2526" );
DEFINE( 2, 0, 1, 1, "\u2527" );
        
DEFINE( 2, 0, 2, 1, "\u2528" );
DEFINE( 1, 0, 2, 2, "\u2529" );
DEFINE( 2, 0, 1, 2, "\u252A" );
DEFINE( 2, 0, 2, 2, "\u252B" );
        
DEFINE( 1, 1, 0, 1, "\u252C" );
DEFINE( 1, 1, 0, 2, "\u252D" );
DEFINE( 1, 2, 0, 1, "\u252E" );
DEFINE( 1, 2, 0, 2, "\u252F" );
        
DEFINE( 2, 1, 0, 1, "\u2530" );
DEFINE( 2, 1, 0, 2, "\u2531" );
DEFINE( 2, 2, 0, 1, "\u2532" );
DEFINE( 2, 2, 0, 2, "\u2533" );
        
DEFINE( 0, 1, 1, 1, "\u2534" );
DEFINE( 0, 1, 1, 2, "\u2535" );
DEFINE( 0, 2, 1, 1, "\u2536" );
DEFINE( 0, 2, 1, 2, "\u2537" );
        
DEFINE( 0, 1, 2, 1, "\u2538" );
DEFINE( 0, 1, 2, 2, "\u2539" );
DEFINE( 0, 2, 2, 1, "\u253A" );
DEFINE( 0, 2, 2, 2, "\u253B" );

DEFINE( 1, 1, 1, 1, "\u253C" );
DEFINE( 1, 1, 1, 2, "\u253D" );
DEFINE( 1, 2, 1, 1, "\u253E" );
DEFINE( 1, 2, 1, 2, "\u253F" );
        
DEFINE( 1, 1, 2, 1, "\u2540" );
DEFINE( 2, 1, 1, 1, "\u2541" );
DEFINE( 2, 1, 2, 1, "\u2542" );
DEFINE( 1, 1, 2, 2, "\u2543" );
        
DEFINE( 1, 2, 2, 1, "\u2544" );
DEFINE( 2, 1, 1, 2, "\u2545" );
DEFINE( 2, 2, 1, 1, "\u2546" );
DEFINE( 1, 2, 2, 2, "\u2547" );
        
DEFINE( 2, 2, 1, 2, "\u2548" );
DEFINE( 2, 1, 2, 2, "\u2549" );
DEFINE( 2, 2, 2, 1, "\u254A" );
DEFINE( 2, 2, 2, 2, "\u254B" );

    // 254C ... 254F -> double dash chars.
    // 2550 ... 256C -> single/double line combos.
    // 256D ... 2570 -> round corners
    // 2571 ... 2573 -> diagonals
    
DEFINE( 0, 0, 0, 1, "\u2574" );
DEFINE( 0, 0, 1, 0, "\u2575" );
DEFINE( 0, 1, 0, 0, "\u2576" );
DEFINE( 1, 0, 0, 0, "\u2577" );
        
DEFINE( 0, 0, 0, 2, "\u2578" );
DEFINE( 0, 0, 2, 0, "\u2579" );
DEFINE( 0, 2, 0, 0, "\u257A" );
DEFINE( 2, 0, 0, 0, "\u257B" );
        
DEFINE( 0, 2, 0, 1, "\u257C" );
DEFINE( 2, 0, 1, 0, "\u257D" );
DEFINE( 0, 1, 0, 2, "\u257E" );
DEFINE( 1, 0, 2, 0, "\u257F" );
